version: '2'
services:
  blockstack-core-1:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './core-1/server/:/root/.blockstack-server/'
      - './core-1/api/:/root/.blockstack/'
    ports:
      - 16264:6264
    restart: always
  blockstack-core-2:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './core-2/server/:/root/.blockstack-server/'
      - './core-2/api/:/root/.blockstack/'
    ports:
      - 16265:6264
    restart: always
  blockstack-core-3:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './core-3/server/:/root/.blockstack-server/'
      - './core-3/api/:/root/.blockstack/'
    ports:
      - 16266:6264
    restart: always
  blockstack-core-4:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './core-4/server/:/root/.blockstack-server/'
      - './core-4/api/:/root/.blockstack/'
    ports:
      - 16267:6264
    restart: always
